### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'size' with random example

### ISSUE THREAD

**Issue by faxinadu** [harveyormston/osc_gen#2]
Running the random generation example I get an error.

`from osc_gen import wavetable
from osc_gen import zosc
from osc_gen import sig
from osc_gen import dsp
from random import uniform

# Create a signal generator.
sg = sig.SigGen()

# Create a wave table with 16 slots to store the waves.
wt = wavetable.WaveTable(num_waves=16)

random_wave = (uniform(-1, 1) for _ in range(128))

# Write to file.
m = sg.arb(random_wave)
wt.waves = [m]
zosc.write_wavetable(wt,'osc_gen_random.h2p')`

**Comment by harveyormston** [comment]
Sorry about that. The waveform handling has been changed to work with numpy arrays now. That example is still creating a generator, which is no longer supported.

I will update the example, but in the meantime, you can do the following instead:

```python
# Generate some random data.
from numpy.random import uniform
random_wave = uniform(-1, 1, 128)
```

**Comment by faxinadu** [comment]
Nice, updated example works thanks.

**Comment by harveyormston** [comment]
Rather than changing the example, I decided being able to support generators and other sequence types is a nice feature to have, so I modified the `arb()` method to attempt conversion to a numpy array instead. (see PR #5)The example should now work as written again.
