### ISSUE TITLE
1 sample missing at the end of each cycle

### ISSUE THREAD

**Issue by faxinadu** [harveyormston/osc_gen#4]
I am not 100% sure this is an issue, apologies beforehand if it is not and simply an error in my code but am getting a small glitch.

Noticed that by default if I use the code below without setting phase, the wavetable starts at the lowest point, I would like instead to start at the zero crossing. 

Using the code below works as I intend, but I end up with a one sample offset at the end of the wave, see attached screenshot. Each cycle results in what seems to be 2047 samples and not 2048.

![exampl](https://user-images.githubusercontent.com/34368899/58704014-3e5a4a00-83b3-11e9-886d-954eb15d470a.png)

`wt_name = 'my_wave.wav'
wt_size = 100
wt_window = 2048

wt = wavetable.WaveTable(num_waves=wt_size)

sig_gen = sig.SigGen()
sig_gen.num_points = wt_window
sig_gen.phase = (2 * np.pi)/4

wt.waves = sig.morph((sig_gen.sin(), sig_gen.tri()), 100)

wavfile.write_wavetable(wt, wt_name)`

**Comment by harveyormston** [comment]
I think this is an issue. I can see the same thing you do with your code. There could be a small error in the end-point of each cycle. I've added a correction to make the cycle transitions smooth, but I want to test it a little first and make sure it's good.

**Comment by harveyormston** [comment]
I have a branch with a potential fix, if you'd like to try it out: #5

**Comment by faxinadu** [comment]
Yes! This seems fixed here, running the same code as the first post here now produces perfect cycles. Thanks!

**Comment by faxinadu** [comment]
I thought of something extra related to this - why not ensure that on all wave shape options, the starting phase is always at the zero crossing, so that if a front-end is built and user moves between selected shapes, the phase behavior is consistent.

**Comment by harveyormston** [comment]
> I thought of something extra related to this - why not ensure that on all wave shape options, the starting phase is always at the zero crossing, so that if a front-end is built and user moves between selected shapes, the phase behavior is consistent.

That makes sense. I've made another update in the branch to implement this.
