### ISSUE TITLE
Is it possible to morph between whole wavetables?

### ISSUE THREAD

**Issue by faxinadu** [harveyormston/osc_gen#7]
Is it possible to?

For example lets say I create a wavetable with a sine and another wavetable with a sample, can I then morph between these?

`#Variables
wt_size_var = 100
wt_window_var = 2048

wt_output = wavetable.WaveTable(num_waves=wt_size_var)
wt_1 = wavetable.WaveTable(num_waves=wt_size_var)   
wt_2 = wavetable.WaveTable(num_waves=wt_size_var)  

sig_gen_1 = sig.SigGen()
sig_gen_1.num_points = 2048

cycle_1 = sig_gen_1.sin()

wt_1.waves = [cycle_1 for _ in range(100)]

wt_2 = wavetable.WaveTable().from_wav('key.wav', resynthesize=False)`

From here, take wt_1 and wt_2 and morph them?

**Comment by faxinadu** [comment]
Also, how does the sample slicer know how many samples each cycle should be? When we use SigGen we tell it with num_points , how is that done for samples?

**Comment by faxinadu** [comment]
ok regarding the second question i found out, 

sig_gen_2 = sig.SigGen()
sig_gen_2.num_points = 2048
wt_2 = wavetable.WaveTable().from_wav('key.wav', resynthesize=False, sig_gen=sig_gen_2)

maybe this should be added to the example, as this is something that is pretty much always going to be needed in real usage.

**Comment by faxinadu** [comment]
ok and for the first question, I found out I can do it like this

wt_output.waves = [np.add(np.multiply(wt_1.get_wave_at_index(i), (wt_output.num_waves - i) / 100.),np.multiply(wt_2.get_wave_at_index(i), (0 + i) / 100.))
	for i in range(wt_output.num_waves)]

1 - is there a better way?
2 - maybe this should be added as a function to the wavetable class

**Comment by harveyormston** [comment]
Your way looks good. You could use the existing morph function on each of the waveforms in the tables, like this:

```python
def morph_wavetables(wta, wtb):
    """ Morph between two wavetables """
    return WaveTable([sig.morph([x, y], 3)[1] for x, y in zip(wta.waves, wtb.waves)])
```

Here's a complete example:

```python
import numpy as np
from osc_gen import sig, dsp, visualize
from osc_gen.wavetable import WaveTable

def morph_wavetables(wta, wtb):
    """ Morph between two wavetables """

    if len(wta.waves) != len(wtb.waves):
        raise ValueError("WaeTables must be the same size")

    return WaveTable([sig.morph([x, y], 3)[1] for x, y in zip(wta.waves, wtb.waves)])


sgen = sig.SigGen()
wt_1 = WaveTable([sgen.sin() for _ in range(16)])
wt_2 = WaveTable([sgen.pls(i / 16) for i in range(16)])
wt_m = morph_wavetables(wt_1, wt_2)
visualize.plot_wavetable(wt_m)
```

This does sound like something useful to have in the wavetable class. I'll look at implementing it there.

**Comment by harveyormston** [comment]
For the morphing question, I've added a new method for this: b2e18ab5a9cfc1f181b748e8512dbcb3d445dbf2.

And, I've updated the example to clarify the need to pass in a `SigGen` when using `from_wav()`:
1b10d1e7207b13e41edc726069fa220620dc7dc9. I also added more `__init__` parameters in `SigGen` to make creating new instances with `num_points` different from the default easier.

Thanks for the suggestions.

**Comment by harveyormston** [comment]
In 8ab1fa3581f0cb5188edc024b72cdb044e4dae09, I've added another example setting `wave_len` when creating the `WaveTable` as an alternative to passing in a `SigGen` object.

```python
wt = wavetable.WaveTable(16, wave_len=2048).from_wav('mywavefile.wav', resynthesize=True)
```

Note that, when creating a `WaveTable`, it is now mandatory to supply the number of slots as the first parameter (16 in the example above).
